### ISSUE TITLE
🚀 Feature[frontend]: (optional) Implement `ProfilePage.jsx`

### ISSUE THREAD

**Issue by bliutech** [bliutech/SeBRUS#29]
### Use Case
We currently have a `/api/user` endpoint that is available for getting information about a user. We will use this sort of information to 

### Proposed Solution
The following is needed to coordinate the implementation of the profile page.

#### Action Items
- [ ] coordinate with backend to add support for an `/api/user/me` specific id to return information about the current user using the corresponding session token. This depends on a few PR so we can hold off on implementing this specific part of the other parts are not ready.
- [ ] write components to display information in `<input>` fields that belong to a user (i.e. username, password, etc). Write a fetch to the backend to get the default values for this page for a user (based on `/api/user/me` endpoint)
- [ ] allow these fields to be modified and add a "Save" button that submits a PUT request to the backend with the update values. Make sure to check that the values are modified or set to default value in the PUT request otherwise this may overwrite the database data for this user
- [ ] (optional) add a default profile image. We may even be able to support profile images by saving the base64 encoded version of an image but not necessary for now.

#### Resources
Reference some other PRs and code for how to maybe implement this.

---

This is a :rocket: Feature Request

**Comment by cy-ros** [comment]
Currently working on it!
